---
# tasks file for role_wordpress
- name: "Création d'un reseau Docker"
  docker_network:
    name: wordpress_network
    state: present

- name: "Création du volume db"
  docker_volume:
    name: "db"
    state: present

- name: "Création du volume wordpress"
  docker_volume:
    name: "wordpress"
    state: present

- name: "Deploiement conteneur MySQL"
  docker_container:
    name: "mysql"
    image: "mariadb"
    state: present
    env:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - name: "wordpress_network"

- name: "Deploiement conteneur Wordpress"
  docker_container:
    name: worpress
    image: wordpress
    state: present
    ports:
      - "8080:80"
    env:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: toto
      WORDPRESS_DB_PASSWORD: toto
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - name: "wordpress_network"