---
# tasks file for role_wordpress
- name: "Création d'un reseau Docker"
  docker_network:
    name: "{{ ntwWordpress }}"
    internal: no
    state: present
    connected:
      - "{{ ctnMysql }}"
      - "{{ ctnWordpress }}"

- name: "Création du volume db"
  docker_volume:
    name: "{{ volDb }}"
    state: present

- name: "Création du volume wordpress"
  docker_volume:
    name: "wordpress"
    state: present

- name: "Deploiement conteneur MySQL"
  docker_container:
    name: "{{ ctnMysql }}"
    image: "mariadb"
    state: present
    env:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "{{ volDb }}:/var/lib/mysql"
    networks:
      - name: "{{ ntwWordpress }}"

- name: "Deploiement conteneur Wordpress"
  docker_container:
    name: "{{ ctnWordpress }}"
    image: wordpress
    state: present
    ports:
      - "{{ exposePort }}:80"
    env:
      WORDPRESS_DB_HOST: "{{ ctnMysql }}"
      WORDPRESS_DB_USER: toto
      WORDPRESS_DB_PASSWORD: toto
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - "wordpress:/var/www/html"
    networks:
      - name: "{{ ntwWordpress }}"