---
# tasks file for role_wordpress
-name: "Création d'un reseau Docker"
   docker_networks:
     name: wordpress_network
     state: present

-name: "Création du volume db"
  docker_volumes:
    name: "db"
    state: present

-name: "Création du volume wordpress"
  docker_volumes:
    name: "wordpress"
    state: present

- name: "Deploiement conteneur MySQL"
  docker_container:
    name: mysql
    restart: always
    image: mariadb
    state: present
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress_network

- name: "Deploiement conteneur Wordpress"
  docker_container:
    name: worpress
    image: wordpress
    restart: always
    state: present
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: toto
      WORDPRESS_DB_PASSWORD: toto
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_network